services:
  reflectabot:
    build: .
    ports:
      - "5211:5211"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5211
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5211/api/update"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
