name: Deploy Bot

on:
    push:
        branches: [main]
    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Deploy to server
              uses: appleboy/ssh-action@v0.1.7
              with:
                  host: ${{ secrets.SERVER_HOST }}
                  username: ${{ secrets.SERVER_USER }}
                  key: ${{ secrets.SERVER_SSH_KEY }}
                  script: |
                      cd /home/${{ secrets.SERVER_USER }}/ReflectaBot

                      echo "Pulling changes..."
                      git pull origin main

                      echo "Stopping containers..."
                      docker-compose down

                      echo "Starting containers..."
                      docker-compose up --build -d

                      echo "Cleaning up..."
                      docker system prune -f

                      echo "Deployment complete"
                      docker-compose ps
